[package]
name = "stry-backend-postgres"
version = "0.1.0"
authors = ["Txuritan <txuritan@protonmail.com>"]
edition = "2018"

description = "The PostgreSQL database backend for stry."
documentation = "https://docs.rs/stry-backend-postgres/"
repository = "https://gitlab.com/stry-rs/backend-postgres"

license = "MIT"

[dependencies]
async-trait = "0.1"
bb8 = "0.7"
bb8-postgres = "0.7"
refinery = { version = "0.5", features = [ "tokio-postgres" ] }
stry-common = "0.1"
