[package]
name = "stry-common"
version = "0.1.3"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

description = "Shared code for stry crates, from backends to frontends, they all depend on this."
documentation = "https://docs.rs/stry-common"
repository = "https://github.com/stry-rs/common"

license = "MIT"

[features]
default = [ "with-backend", "with-nanoid" ]

with-backend = [ "async-trait" ]
with-nanoid = [ "rand" ]

[dependencies]
arrayvec = { version = "0.5", features = [ "serde" ] }
async-trait = { version= "0.1", optional = true }
chrono = { version = "0.4", features = [ "serde" ] }
either = { version = "1.6", features = [ "serde" ] }
percent-encoding = "2.1"
rand = { version = "0.8", optional = true }
serde = { version = "1.0", features = [ "derive" ] }
