[workspace]
members = [
    "xtask",

    # 'external' crates
    "attrouter",
    "attrouter/tests-warp",
    "evermore",
    "remark",

    # stry crates
    "backend-postgres",
    "common",
]