[workspace]
resolver = "2"
members = [
    "xtask",

    # 'external' crates
    "evermore",
    "syndrome",

    # stry crates
    "stry-analytics",
    "stry-backend-postgres",
    "stry-common",
    "stry-macros",
    "stry-service-json",
]
