[package]
name = "xtask"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
