[package]
name = "stry-remark"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

description = "A HTML to Markdown converter and soon to be formatter."

license = "MIT"

[features]
default = [ "with-rcdom" ]
with-arcdom = [ "markup5ever_arcdom" ]
with-rcdom = [ "markup5ever_rcdom" ]

[dependencies]
anyhow = "1.0"
html5ever = "0.25"
markup5ever = "0.10"
markup5ever_arcdom = { version = "0.1", optional = true }
markup5ever_rcdom = { version = "0.1", optional = true }
thiserror = "1.0"
