[package]
name = "cold-clouds"
version = "0.1.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[dependencies]
swc_common = { version = "0.10", features = [ "tty-emitter" ] }
swc_ecma_ast = "0.43"
swc_ecma_parser = "0.54"
